# Generated by Django 2.1 on 2018-08-05 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('verb', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=5)),
                ('response_code', models.CharField(max_length=100)),
                ('content_type', models.CharField(choices=[('text/plain', 'text/plain'), ('text/html', 'text/html'), ('application/json', 'application/jsonT')], max_length=17)),
                ('encoding', models.CharField(choices=[('UTF-8', 'UTF-8'), ('UTF-16', 'UTF-16'), ('ISO-8859-1', 'ISO-8859-1')], max_length=10)),
                ('body', models.CharField(blank=True, max_length=1000)),
                ('external_service_address', models.CharField(blank=True, max_length=100)),
                ('external_service_login', models.CharField(blank=True, max_length=100)),
                ('external_service_token', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
